### ISSUE TITLE
Issue & Bug

### ISSUE THREAD

**Issue by shadowTW** [GouveiaXS/angelicxs-RandomBox#1]
https://streamable.com/ize7qq

**Comment by GouveiaXS** [comment]
Please provide more details; the function to remove the item is in the server side. What is your framework? What is your inventory?

**Comment by shadowTW** [comment]
qb-core and i use the default inventory from qb, qb-inventory

**Comment by GouveiaXS** [comment]
Are there any server side or client side errors showing up on your console? I pulled this direct version into a blank qb server and it worked as intended.

**Comment by StruggleBus-Tv** [comment]
I'm having the exact same problem as this. Any idea what the issue was?

**Comment by GouveiaXS** [comment]
Issue has been resolved with the latest server side commitment.
