### ISSUE TITLE
Bad design.

### ISSUE THREAD

**Issue by RayaanUddin** [GouveiaXS/angelicxs-RandomBox#2]
Since the event of opening a box is on server ...
RegisterServerEvent('angelicxs-randombox:server:OpenBox')
AddEventHandler('angelicxs-randombox:server:OpenBox', function(source, tier, amount)
    local src = source
    math.randomseed(os.time())
    local item = randomizer(tier)
    CreateThread(function()
        if Config.AllowGeneralLoot then
            local times = 0
            while times ~= amount do
                generalloot(src)
                times = times + 1
                if times == amount then
                    break
                end
                Wait(10)
            end
        end
    end)
    if Config.UseESX then
        local xPlayer = ESX.GetPlayerFromId(src)
		xPlayer.addInventoryItem(item.name, item.amount)
    elseif Config.UseQBCore then
        local Player = QBCore.Functions.GetPlayer(src)
        Player.Functions.AddItem(item.name, item.amount)
    end
    TriggerClientEvent('angelicxs-randombox:Notify',src, Config.Lang['receive']..item.amount..' '..item.name, Config.LangType['success'])
end)

It makes the server crash when multiple people open it at around the same time, due to Wait. This is bad since this script is used to be given to new players by most servers, and it will most likely be used when so do alot of people.

**Comment by GouveiaXS** [comment]
While I have never encountered this issue myself or have been informed of an issue while multiple people were spam opening the the item, you are more then welcome to make a fork of your own with an improved design for others to use.
